In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('text_with_scores.csv')

In [3]:
df.head()

,Unnamed: 0,review,rating,text,company,roberta_neg,roberta_neu,roberta_pos
0,0,PERFECTION,5,First: you had the books I wanted for a gift t...,bookshop.org,0.002093,0.029654,0.968253
1,1,Good book buying experience,5,Great communication about my order. Books arri...,bookshop.org,0.003136,0.015224,0.981640
2,2,I appreciate the selection and the…,5,I appreciate the selection and the prices of t...,bookshop.org,0.002250,0.018527,0.979223
3,3,The books arrived in a very timely…,5,The books arrived in a very timely fashion and...,bookshop.org,0.005400,0.146323,0.848277
4,4,"Quick delivery, fab products",5,Beautiful books delivered extremely quickly co...,bookshop.org,0.001641,0.010469,0.987889

In [4]:
df.columns

Index(['Unnamed: 0', 'review', 'rating', 'text', 'company', 'roberta_neg',
       'roberta_neu', 'roberta_pos'],
      dtype='object')

In [5]:
import pandas as pd

# Assuming df is your DataFrame
def get_sentiment_and_compare(row):
    # Get the highest sentiment from RoBERTa
    roberta_scores = [row['roberta_neg'], row['roberta_neu'], row['roberta_pos']]
    sentiments = ['negative', 'neutral', 'positive']
    
    # Get the index of the highest sentiment
    highest_score_index = roberta_scores.index(max(roberta_scores))
    predicted_sentiment = sentiments[highest_score_index]
    
    # Compare the predicted sentiment with the actual rating
    # Assuming the rating is 1 for negative, 3 for neutral, and 5 for positive
    if predicted_sentiment == 'negative' and row['rating'] <= 2:
        match = True
    elif predicted_sentiment == 'neutral' and row['rating'] == 3:
        match = True
    elif predicted_sentiment == 'positive' and row['rating'] >= 4:
        match = True
    else:
        match = False
    
    return predicted_sentiment, match

# Apply the function to each row and create new columns for the predicted sentiment and comparison
df[['predicted_sentiment', 'match']] = df.apply(get_sentiment_and_compare, axis=1, result_type='expand')

# Display the updated DataFrame
print(df[['review', 'predicted_sentiment', 'rating', 'match']].head())

                                review predicted_sentiment  rating  match
0                           PERFECTION            positive       5   True
1          Good book buying experience            positive       5   True
2  I appreciate the selection and the…            positive       5   True
3  The books arrived in a very timely…            positive       5   True
4         Quick delivery, fab products            positive       5   True

In [7]:
mismatches = df[df['match'] == False]
mismatches

,Unnamed: 0,review,rating,text,company,roberta_neg,roberta_neu,roberta_pos,predicted_sentiment,match
64,64,Kia Sportage hire from Heathrow T5.,4,Pickup from Heathrow was seamless; great commu...,humble-hire.com,0.251494,0.504514,0.243992,neutral,False
81,81,The shipping was free and arrived in a…,4,The shipping was free and arrived in a timely ...,www.watersportsoutlet.com,0.168650,0.596523,0.234828,neutral,False
85,85,Package came as ordered but watch out for taxes,5,Package came as ordered. Be careful though if ...,www.watersportsoutlet.com,0.459353,0.488103,0.052544,neutral,False
86,86,All smooth and professional,5,All smooth and professional. Is there a place ...,www.watersportsoutlet.com,0.013139,0.583000,0.403861,neutral,False
96,96,Better if you lower down the price on…,5,Better if you lower down the price on invoice ...,www.watersportsoutlet.com,0.226075,0.618402,0.155523,neutral,False
...,...,...,...,...,...,...,...,...,...,...
139913,140032,"Color Spotting--peruse your murals right away,...",3,"The ordering, the repositioning of the mural t...",muralsyourway.com,0.164464,0.384753,0.450783,positive,False
139915,140034,I was disappointed to learn that the… See UPDATE!,1,I was disappointed to learn that the edges did...,muralsyourway.com,0.219986,0.334676,0.445338,positive,False
139917,140036,To get the width I needed the scene…,3,To get the width I needed the scene became blu...,muralsyourway.com,0.627963,0.354202,0.017835,negative,False
139933,140052,Very Knowledgeable,5,I pick out several different fish was about to...,www.theifishstore.com,0.449444,0.481783,0.068773,neutral,False
140004,140123,Great service and great product,5,"Date of experience: November 29, 2024",cbdoflawrence.com,0.019454,0.930186,0.050360,neutral,False